### ISSUE TITLE
ur status cmds are whack, yo

### ISSUE THREAD

**Issue by Dieterbe** [RichiH/vcsh_mr_template#1]
with a vcsh repo definition in mr like the sample config, i get this:

```
19:30:09 dieter@Gi ~ mr status
mr status: /home/dieter/.config/vcsh/repo.d/vcsh_mr.git
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#   new file:   ../../../mr/available.d/gnupg.vcsh
#   deleted:    ../../../mr/available.d/mr.vcsh
#   new file:   ../../../mr/available.d/oh-my-zsh.git
#   new file:   ../../../mr/available.d/pim.git
#   new file:   ../../../mr/available.d/vcsh_mr.vcsh
#   new file:   ../../../mr/available.d/vim.git
#   modified:   ../../../mr/available.d/zsh.vcsh
#   new file:   ../../../mr/config.d/gnupg.vcsh
#   deleted:    ../../../mr/config.d/mr.vcsh
#   new file:   ../../../mr/config.d/oh-my-zsh.git
#   new file:   ../../../mr/config.d/pim.git
#   new file:   ../../../mr/config.d/vcsh_mr.vcsh
#   new file:   ../../../mr/config.d/vim.git
#   new file:   ../../../mr/config.d/zsh.vcsh
#   deleted:    ../../../../.gitignore
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   ../../../../.mrconfig
#

```

I.e. mr runs `vcsh run <repo> git status` from the directory of the repo itself.
To get the normal output (i.e. relative to $HOME) I need to use status definitions like this:

```
status = cd ; vcsh run vcsh_mr git status
```

**Comment by RichiH** [comment]
From what directory did you execute this? I am not having any issue like this.

The $PWD-reliance of vcsh is a feature, not a bug. It would be trivial to just `cd $HOME` at the start of everything, but then you couldn't

```
cd ~/.zsh
vcsh zsh add foo
```

instead you would need to

```
cd ~/.zsh
vcsh zsh add .zsh/foo
```

**Comment by Dieterbe** [comment]
i run `mr status` in $HOME.

**Comment by RichiH** [comment]
Are you using my template to seed your own config (looks like...).

In that case, `cd; vcsh mr add .config/mr/available.d/*; vcsh mr commit` to add your new config files.

**Comment by Dieterbe** [comment]
Yes, like I said in my first post.

This report is about the status cmd including `../../..` for each file.

**Comment by RichiH** [comment]
OK, that took some time ;)

As with other commands, depending on $PWD is a feature, not a bug. Only a select few commands will switch to $HOME before being executed, status is not among them.

This will be handled in the mr patch to support vcsh, not in vcsh itself.

**Comment by Dieterbe** [comment]
why? what is useful about this status format?
it makes no sense, if i run `mr status` in $HOME, i want to view the files in the status output to be seen from $HOME, so that:
- the filenames are actually correct as seen from $HOME
- i can copy paste a filename from `mr status` output and prepend `vim` or `git add` to it.
- not to mention the bogus `../../..` doesn't have any purpose, nor is it even useful at all. as I will never navigate to ~/.config/vcsh/repo.d/<myrepo> and `git add` or whatever from there.

**Comment by RichiH** [comment]
vcsh needs to take $PWD into account as you don't want to see '.zsh/foo' but 'foo' when doing `vcsh zsh status` in $HOME/.zsh .

mr executes everything relative to $MR_REPO which is why you end up seeing the prefix.

**Comment by Dieterbe** [comment]
"mr executes everything relative to $MR_REPO which is why you end up seeing the prefix."
I know that.... That's what I'm saying since the first post of this report.

I'm also saying it's ugly and not useful at all.  And I never said anything needs to change within vcsh.  Vcsh's reliance on pwd is good.

**Comment by RichiH** [comment]
(handled via IRC)

**Comment by Dieterbe** [comment]
it looks like this is fixed since the introduction of the vcsh.vcsh = true setting in vcsh repositories, along with mr support for vcsh (i.e. since https://github.com/RichiH/vcsh_mr_template/commit/c5d30352e598c3585070a41df48d547d4ec87326)
